name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    name: Validar Sintaxe do Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Verificar Sintaxe do Script
        id: check_syntax
        run: |
          bash -n status-check.sh || echo "::error file=status-check.sh::Erro de sintaxe encontrado no status-check.sh. Por favor, verifique."
          echo "::warning title=Validação::Verificação de sintaxe concluída, mas considere adicionar mais testes estáticos."

      - name: Resumo do Job Validate
        run: |
          echo "### Resumo da Validação" >> $GITHUB_STEP_SUMMARY
          echo "- **Ambiente (OS):** ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch/Tag:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Resultado da verificação de sintaxe:** ${{ steps.check_syntax.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

  test:
    name: Executar Testes
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Simular Execução de Testes
        id: run_tests
        run: |
          echo "Running tests..."
          echo "Testes concluídos com sucesso (simulação)."
          exit 0

      - name: Resumo do Job Test
        run: |
          echo "### Resumo dos Testes" >> $GITHUB_STEP_SUMMARY
          echo "- **Ambiente (OS):** ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch/Tag:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Resultado dos testes:** ${{ steps.run_tests.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

  package:
    name: Gerar e Fazer Upload do Artefato
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Gerar Artefato
        id: generate_artifact
        run: |
          echo "Este é o conteúdo do relatório de testes." > report.txt
          zip -r report.zip report.txt
          echo "::warning title=Artefato::Relatório gerado com sucesso, mas considere um formato mais robusto."

      - name: Fazer Upload do Artefato
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.zip

      - name: Resumo Completo do Workflow
        run: |
          echo "## Resumo Geral do CI Workflow" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Informações do Ambiente" >> $GITHUB_STEP_SUMMARY
          echo "- **Sistema Operacional do Runner:** ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch/Tag Acionadora:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **ID da Execução:** ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Link da Execução:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Resultados dos Jobs" >> $GITHUB_STEP_SUMMARY
          echo "- **Job Validate:** ${{ needs.validate.result }}" >> $GITHUB_STEP_SUMMARY
          echo "  - _Sintaxe Verificada:_ ${{ steps.check_syntax.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Job Test:** ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "  - _Testes Executados:_ ${{ steps.run_tests.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Job Package:** ${{ needs.package.result }}" >> $GITHUB_STEP_SUMMARY
          echo "  - _Artefato Gerado:_ ${{ steps.generate_artifact.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "  - _Artefato Enviado:_ ${{ steps.upload_artifact.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Artefatos" >> $GITHUB_STEP_SUMMARY
          echo "Os artefatos estão disponíveis na seção 'Summary' (Resumo) desta execução do workflow." >> $GITHUB_STEP_SUMMARY
          echo "[Link para Artefatos (nesta mesma página)](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
